--[[
ask_pane_mapping_zone_matrix
Purpose: Define the ask-pane mapping and command contract by user location.
Does: Lists representative active mappings and commands by project, Markdown, terminal, and ask-pane zones.
Architecture: Kept as a test fixture so docs and focused regressions can share one compact source of truth.
]]

return {
    required_zones = {
        "project buffer",
        "Markdown pane",
        "terminal pane",
        "ask pane",
    },
    required_mappings = {
        "ask_pane",
        "ask",
        "ask_last",
        "ask_codex",
        "ask_claude",
        "ask_submit",
        "ask_send",
        "ask_send_alt",
        "ask_model_picker",
        "ask_model_picker_alt",
        "ask_next_file",
        "ask_previous_file",
        "ask_next_selection",
        "ask_previous_selection",
        "ask_source",
        "help",
        "headings",
        "toggle_terminal",
        "toggle_terminal_alt",
    },
    required_commands = {
        "SidepanesAsk",
        "SidepanesAskAppend",
        "SidepanesAskStatus",
        "SidepanesSubmitQuestion",
        "SidepanesVersion",
        "SidepanesMappings",
    },
    planned_commands = {},
    rows = {
        {
            id = "project-global-normal-ask-pane",
            zone = "project buffer",
            mode = "normal",
            mapping = "ask_pane",
            default_lhs = "<leader>pa",
            result = "show or focus ask pane",
        },
        {
            id = "project-global-visual-ask",
            zone = "project buffer",
            mode = "visual",
            mapping = "ask",
            default_lhs = "<leader>pa",
            result = "capture selection through ask picker or active ask draft",
        },
        {
            id = "project-global-visual-ask-shortcuts",
            zone = "project buffer",
            mode = "visual",
            mapping = "ask_last, ask_codex, ask_claude",
            default_lhs = "aa, ax, ac",
            result = "capture selection for last, Codex, or Claude target",
        },
        {
            id = "markdown-pane-heading-and-ask",
            zone = "Markdown pane",
            mode = "normal",
            mapping = "headings, ask_pane, help",
            default_lhs = "fm, ap, gh",
            result = "open heading picker, switch to ask pane, or show mapping help",
        },
        {
            id = "markdown-pane-visual-ask",
            zone = "Markdown pane",
            mode = "visual",
            mapping = "ask_last, ask_codex, ask_claude",
            default_lhs = "aa, ax, ac",
            result = "capture selected Markdown text for agent ask",
        },
        {
            id = "markdown-pane-terminal-toggles",
            zone = "Markdown pane",
            mode = "normal",
            mapping = "toggle_terminal, toggle_terminal_alt",
            default_lhs = "<leader>gg, <C-g>",
            result = "toggle from Markdown to the last terminal pane",
        },
        {
            id = "terminal-pane-ask-and-toggles",
            zone = "terminal pane",
            mode = "normal",
            mapping = "ask_pane, toggle_terminal, toggle_terminal_alt, help",
            default_lhs = "ap, <leader>gg, <C-g>, gh",
            result = "open ask pane, return to Markdown/terminal counterpart, or show mapping help",
        },
        {
            id = "terminal-pane-terminal-mode-toggles",
            zone = "terminal pane",
            mode = "terminal",
            mapping = "toggle_terminal, toggle_terminal_alt",
            default_lhs = "<leader>gg, <C-g>",
            result = "toggle safely while terminal input mode is active",
        },
        {
            id = "terminal-pane-quit-command",
            zone = "terminal pane",
            mode = "command",
            mapping = ":q, :quit",
            default_lhs = "command path used by personal mappings such as <leader>qq -> :q<CR>",
            result = "show Markdown instead of closing the pane or triggering ask-pane send",
        },
        {
            id = "ask-pane-target-picker",
            zone = "ask pane",
            mode = "normal",
            mapping = "ask_model_picker, ask_model_picker_alt, help",
            default_lhs = "M, <Tab>, gh",
            result = "open ask target/model picker or show mapping help",
        },
        {
            id = "ask-pane-submit-and-send",
            zone = "ask pane",
            mode = "normal/insert",
            mapping = "ask_submit, ask_send, ask_send_alt",
            default_lhs = "<C-CR>, disabled, disabled",
            result = "submit current prompt or run the ask-pane quit lifecycle",
        },
        {
            id = "ask-pane-command-line",
            zone = "ask pane",
            mode = "command",
            mapping = ":q, :q!, :w, :wq, :x, :exit",
            default_lhs = "command-line path",
            result = "write, cancel, or submit through ask-pane lifecycle",
        },
        {
            id = "ask-pane-context-navigation",
            zone = "ask pane",
            mode = "normal",
            mapping = "ask_next_file, ask_previous_file, ask_next_selection, ask_previous_selection, ask_source",
            default_lhs = "]f, [f, ]s, [s, gf",
            result = "move through citations or jump to cited source",
        },
        {
            id = "ask-zone-commands",
            zone = "project buffer, Markdown pane, terminal pane, ask pane",
            mode = "command",
            mapping = "SidepanesAsk, SidepanesAskAppend, SidepanesAskStatus, SidepanesSubmitQuestion, SidepanesVersion, SidepanesMappings",
            default_lhs = ":SidepanesAsk, :SidepanesAskAppend, :SidepanesAskStatus, :SidepanesSubmitQuestion, :SidepanesVersion, :SidepanesMappings",
            result = "range-aware ask, explicit append, active draft status, active draft submit, version debugging, or mapping help",
        },
    },
}
