--[[
ask_pane_behavior_matrix
Purpose: Define the ask-pane lifecycle contract used by roadmap and docs tests.
Does: Lists required actions, pane zones, draft states, expected results, aliases, and representative behavior rows.
Architecture: Kept separate from runtime modules so the behavior contract can be checked without opening Neovim UI state.
]]

return {
    required_actions = {
        ":q",
        ":q!",
        ":w",
        ":wq",
        ":x",
        ":exit",
        "qq",
        "<leader>qq",
        "<C-CR>",
        "SidepanesSubmitQuestion",
    },
    required_aliases = {
        ":quit",
        ":quit!",
        ":xit",
        "mappings.pane.ask_send",
        "mappings.pane.ask_send_alt",
    },
    required_zones = {
        "project buffer",
        "Markdown pane",
        "terminal pane",
        "ask pane",
    },
    required_states = {
        "ready_empty",
        "draft_modified",
        "draft_written",
        "sending_picker",
        "sending_terminal",
        "send_failed",
        "cancelled",
        "sent",
    },
    required_results = {
        "cancel",
        "warn/keep",
        "write",
        "send",
        "restore previous pane",
        "switch to target terminal",
        "show Markdown",
    },
    rows = {
        {
            id = "ask-q-ready",
            action = ":q",
            aliases = { ":quit" },
            zone = "ask pane",
            state = "ready_empty -> cancelled",
            results = { "cancel", "restore previous pane" },
        },
        {
            id = "ask-q-modified",
            action = ":q",
            aliases = { ":quit" },
            zone = "ask pane",
            state = "draft_modified -> cancelled",
            results = { "cancel", "restore previous pane" },
        },
        {
            id = "ask-q-written",
            action = ":q",
            aliases = { ":quit" },
            zone = "ask pane",
            state = "draft_written -> sending_terminal -> sent",
            results = { "send", "switch to target terminal" },
        },
        {
            id = "ask-q-failed-send",
            action = ":q",
            aliases = { ":quit" },
            zone = "ask pane",
            state = "send_failed -> sending_terminal or send_failed",
            results = { "send", "warn/keep" },
        },
        {
            id = "ask-qbang-any",
            action = ":q!",
            aliases = { ":quit!" },
            zone = "ask pane",
            state = "ready_empty, draft_modified, draft_written, send_failed -> cancelled",
            results = { "cancel", "restore previous pane" },
        },
        {
            id = "ask-write-ready",
            action = ":w",
            aliases = {},
            zone = "ask pane",
            state = "ready_empty -> draft_written",
            results = { "write" },
        },
        {
            id = "ask-write-draft",
            action = ":w",
            aliases = {},
            zone = "ask pane",
            state = "draft_modified, draft_written, send_failed -> draft_written",
            results = { "write" },
        },
        {
            id = "ask-write-quit-ready",
            action = ":wq",
            aliases = { ":wq!", ":x", ":xit", ":exit" },
            zone = "ask pane",
            state = "ready_empty -> draft_written -> cancelled",
            results = { "write", "cancel", "restore previous pane" },
        },
        {
            id = "ask-write-quit-draft",
            action = ":wq",
            aliases = { ":wq!", ":x", ":xit", ":exit" },
            zone = "ask pane",
            state = "draft_modified, draft_written, send_failed -> draft_written, sending_picker, sending_terminal, sent, send_failed",
            results = { "write", "send", "switch to target terminal", "warn/keep" },
        },
        {
            id = "ask-send-shortcut-unwritten",
            action = "qq",
            aliases = { "mappings.pane.ask_send" },
            zone = "ask pane",
            state = "ready_empty, draft_modified -> cancelled",
            results = { "cancel", "restore previous pane" },
        },
        {
            id = "ask-send-shortcut-written",
            action = "qq",
            aliases = { "mappings.pane.ask_send" },
            zone = "ask pane",
            state = "draft_written, send_failed -> sending_terminal, sent, send_failed",
            results = { "send", "switch to target terminal", "warn/keep" },
        },
        {
            id = "ask-send-alt-shortcut",
            action = "<leader>qq",
            aliases = { "mappings.pane.ask_send_alt" },
            zone = "ask pane",
            state = "ready_empty, draft_modified, draft_written, send_failed -> cancelled, sending_terminal, sent, send_failed",
            results = { "cancel", "restore previous pane", "send", "switch to target terminal", "warn/keep" },
        },
        {
            id = "non-ask-quit-command",
            action = ":q",
            aliases = { ":quit" },
            zone = "Markdown pane, terminal pane",
            state = "not ask draft state",
            results = { "show Markdown" },
        },
        {
            id = "ask-submit-ready",
            action = "<C-CR>",
            aliases = { "mappings.pane.ask_submit" },
            zone = "ask pane",
            state = "ready_empty -> draft_written -> cancelled",
            results = { "write", "cancel", "restore previous pane" },
        },
        {
            id = "ask-submit-draft",
            action = "<C-CR>",
            aliases = { "mappings.pane.ask_submit" },
            zone = "ask pane",
            state = "draft_modified, draft_written, send_failed -> draft_written, sending_terminal, sent, send_failed",
            results = { "write", "send", "switch to target terminal", "warn/keep" },
        },
        {
            id = "submit-command-no-draft",
            action = "SidepanesSubmitQuestion",
            aliases = { ":Sidepanes submit-question" },
            zone = "project buffer, Markdown pane, terminal pane, ask pane",
            state = "no active ask draft",
            results = { "warn/keep" },
        },
        {
            id = "submit-command-active-draft",
            action = "SidepanesSubmitQuestion",
            aliases = { ":Sidepanes submit-question" },
            zone = "project buffer, Markdown pane, terminal pane, ask pane",
            state = "ready_empty, draft_modified, draft_written, send_failed -> draft_written, sending_terminal, sent, send_failed",
            results = { "write", "send", "switch to target terminal", "warn/keep" },
        },
        {
            id = "non-ask-command-line",
            action = ":q, :q!, :w, :wq, :x, :exit",
            aliases = { ":quit", ":quit!", ":xit" },
            zone = "project buffer, Markdown pane, terminal pane",
            state = "not ask draft state",
            results = { "not intercepted by ask-pane lifecycle" },
        },
    },
}
